name: Unit Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [closed]
  schedule:
    - cron: '0 0 * * 0'

jobs:
  code-styles:
    name: Python ${{ matrix.python-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        python-version: [ '3.13', '3.12', '3.11', '3.10', '3.9' ]
        operating-system: [ ubuntu-22.04 ]

    steps:
      - name: Setup Python
        # Commit hash for v5.5.0: https://github.com/actions/setup-python/releases/tag/v5.5.0
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Checkout fail2slack
        # Commit hash for v3.5.3: https://github.com/actions/checkout/releases/tag/v4.2.2
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Log Debug Information
        run: |
          echo "$GITHUB_REF"
          echo "$GITHUB_EVENT_NAME"
          python --version
          pip --version

      - name: Run Tests
        run: |
          python -m unittest -v
